#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2026 Gustavo Amigo
#
# generate_tests.py — Generates prove_plugin.cpp from the scenario matrix.
#
# Usage:
#   python3 -m tests.proof.generate_tests
#   (from bytecaskdb-mariadb-plugin/)

import sys
from pathlib import Path
from textwrap import dedent

from .scenario_matrix import (
    DMLShape, IndexShape, TxnShape, PluginFailureClass, generate_matrix
)
from .expected_delta import expected_delta
from .fault_point_resolver import resolve_fault

HEADER = '''\
// SPDX-License-Identifier: GPL-2.0-only
// Copyright (c) 2026 Gustavo Amigo
//
// prove_plugin.cpp — AUTO-GENERATED by tests/proof/generate_tests.py
// DO NOT EDIT BY HAND. Regenerate with:
//   cd bytecaskdb-mariadb-plugin && python3 -m tests.proof.generate_tests

#include "harness.h"
#include "fault_injector.h"

#include <catch2/catch_test_macros.hpp>
#include <system_error>

using namespace bytecaskdb::testing;
using namespace bytecask::testing;

'''


def table_spec_code(index: IndexShape) -> str:
    lines = ["TableSpec spec;", "spec.num_int_columns = 3;", "spec.has_pk = true;"]
    if index == IndexShape.one_nonunique:
        lines.append(
            "spec.secondary_indexes.push_back({1, 1, false, {1}});"
        )
    elif index == IndexShape.one_unique:
        lines.append(
            "spec.secondary_indexes.push_back({1, 1, true, {1}});"
        )
    return "\n  ".join(lines)


def setup_code(dml: DMLShape) -> str:
    """Code to set up pre-existing rows needed for update/delete."""
    if dml in (DMLShape.single_delete, DMLShape.single_update_index_change,
               DMLShape.single_update_no_index_change,
               DMLShape.single_update_pk_change):
        return dedent("""\
            // Pre-insert a row to operate on.
            REQUIRE(h.insert_row({10, 20, 30}) == 0);
            REQUIRE(h.commit() == 0);
        """).rstrip()
    return ""


def dml_call(dml: DMLShape, failure: PluginFailureClass) -> str:
    """Generate the DML call, wrapping in try-catch for DML-time faults."""
    raw_call = _raw_dml_call(dml)
    if failure in dml_failure_classes():
        # Wrap in try-catch — the fault throws std::system_error.
        return f"bool threw = false;\n  try {{\n    {raw_call}\n    (void)rc;\n  }} catch (const std::system_error &) {{\n    threw = true;\n  }}"
    return raw_call


def _raw_dml_call(dml: DMLShape) -> str:
    if dml == DMLShape.single_insert:
        return "int rc = h.insert_row({100, 200, 300});"
    elif dml == DMLShape.single_delete:
        return "int rc = h.delete_row({10, 20, 30});"
    elif dml == DMLShape.single_update_index_change:
        return "int rc = h.update_row({10, 20, 30}, {10, 99, 30});"
    elif dml == DMLShape.single_update_no_index_change:
        # Change col[2] (not indexed) from 30 to 99.
        return "int rc = h.update_row({10, 20, 30}, {10, 20, 99});"
    elif dml == DMLShape.single_update_pk_change:
        # Change the PK column (col[0]) from 10 to 50.
        return "int rc = h.update_row({10, 20, 30}, {50, 20, 30});"
    elif dml == DMLShape.multi_row_insert:
        return "int rc = h.insert_row({100, 200, 300});\n    if (rc == 0) rc = h.insert_row({101, 201, 301});\n    if (rc == 0) rc = h.insert_row({102, 202, 302});"
    return "int rc = 0;"


def fault_setup(failure: PluginFailureClass, dml: DMLShape) -> str:
    config = resolve_fault(failure)
    if config.injector_name:
        return f'ScopedFaultInjector guard("{config.injector_name}");'
    return ""


def occ_conflict_injection(failure: PluginFailureClass, dml: DMLShape) -> str:
    """For OCC_CONFLICT, inject a concurrent write after DML (before commit)."""
    if failure != PluginFailureClass.OCC_CONFLICT:
        return ""
    # Write the same key the DML operated on — creates W-W conflict.
    if dml in (DMLShape.single_delete, DMLShape.single_update_index_change,
               DMLShape.single_update_no_index_change,
               DMLShape.single_update_pk_change):
        return "h.inject_concurrent_write({10, 20, 30});"
    elif dml == DMLShape.single_insert:
        return "h.inject_concurrent_write({100, 200, 300});"
    elif dml == DMLShape.multi_row_insert:
        return "h.inject_concurrent_write({100, 200, 300});"
    return ""


def commit_failure_classes():
    """Failure classes where fault fires at commit time (not during DML)."""
    return {
        PluginFailureClass.ENGINE_DEGRADED,
        PluginFailureClass.ENGINE_IO_FAIL,
        PluginFailureClass.OCC_CONFLICT,
    }


def dml_failure_classes():
    """Failure classes where fault fires during DML (DML throws)."""
    return {
        PluginFailureClass.PLUGIN_INDEX_HALF_BUFFERED,
    }


def fault_teardown(failure: PluginFailureClass, txn: TxnShape) -> str:
    """Code after DML for failure classes that fire at commit."""
    if failure in commit_failure_classes():
        return "int commit_rc = h.commit();"
    return ""


def txn_wrapper_pre(txn: TxnShape, dml: DMLShape) -> str:
    """Code before the main DML for multi_statement / with_savepoint."""
    if txn == TxnShape.multi_statement:
        return dedent("""\
            // First statement in multi-statement txn.
            REQUIRE(h.insert_row({1, 2, 3}) == 0);
            h.stmt_boundary();
        """).rstrip()
    elif txn == TxnShape.with_savepoint:
        return dedent("""\
            // Insert a row, then set savepoint (simulated via commit+re-begin).
            REQUIRE(h.insert_row({1, 2, 3}) == 0);
            h.stmt_boundary();
        """).rstrip()
    return ""


def committed_row_count(dml: DMLShape) -> int:
    """Row count after setup commits (before current transaction starts)."""
    if dml in (DMLShape.single_delete, DMLShape.single_update_index_change,
               DMLShape.single_update_no_index_change,
               DMLShape.single_update_pk_change):
        return 1
    return 0


def expected_final_count(dml: DMLShape, txn: TxnShape,
                         failure: PluginFailureClass) -> int:
    """Expected row counter after the test completes."""
    base = committed_row_count(dml)
    delta = expected_delta(dml, IndexShape.pk_only, txn, failure)

    if failure != PluginFailureClass.SUCCESS:
        # Failed transaction — everything in current txn is rolled back.
        # Counter reverts to committed baseline.
        return base

    # SUCCESS: current transaction commits.
    txn_pre_delta = 0
    if txn in (TxnShape.multi_statement, TxnShape.with_savepoint):
        txn_pre_delta = 1  # pre-insert of {1,2,3}

    return base + txn_pre_delta + delta.row_count_delta


def assertions(dml: DMLShape, index: IndexShape, txn: TxnShape,
               failure: PluginFailureClass) -> str:
    lines = []
    base = committed_row_count(dml)
    final = expected_final_count(dml, txn, failure)

    if failure in commit_failure_classes():
        lines.append("// DML buffers successfully; fault fires at commit.")
        lines.append("REQUIRE(rc == 0);")
        lines.append("REQUIRE(commit_rc != 0);")
        lines.append(f"REQUIRE(h.row_counter() == {base});")
    elif failure in dml_failure_classes():
        lines.append("// Fault fires during DML; exception caught, state rolled back.")
        lines.append("REQUIRE(threw);")
        lines.append("h.rollback();")
        lines.append(f"REQUIRE(h.row_counter() == {base});")
    else:
        # SUCCESS path.
        lines.append("REQUIRE(rc == 0);")
        lines.append(f"REQUIRE(h.row_counter() == {final});")

    return "\n  ".join(lines)


def generate_test_case(dml: DMLShape, index: IndexShape,
                       txn: TxnShape, failure: PluginFailureClass) -> str:
    name = f"prove_plugin__{dml.name}__{index.name}__{txn.name}__{failure.name}"
    tag = "[prove_plugin]"

    spec = table_spec_code(index)
    setup = setup_code(dml)
    txn_pre = txn_wrapper_pre(txn, dml)
    fault = fault_setup(failure, dml)
    call = dml_call(dml, failure)
    occ_inject = occ_conflict_injection(failure, dml)
    teardown = fault_teardown(failure, txn)
    asserts = assertions(dml, index, txn, failure)

    body_parts = [f"  {spec}", "  PluginTestHarness h(spec);"]
    if setup:
        body_parts.append(f"  {setup}")
    if txn_pre:
        body_parts.append(f"  {txn_pre}")
    if fault:
        body_parts.append(f"  {fault}")
    body_parts.append(f"  {call}")
    if occ_inject:
        body_parts.append(f"  {occ_inject}")
    if teardown:
        body_parts.append(f"  {teardown}")
    body_parts.append(f"  {asserts}")

    body = "\n\n".join(body_parts)

    return f'TEST_CASE("{name}", "{tag}") {{\n{body}\n}}\n'


def main():
    output_dir = Path(__file__).parent / "generated"
    output_dir.mkdir(exist_ok=True)
    output_path = output_dir / "prove_plugin.cpp"

    tests = []
    for scenario in generate_matrix():
        tests.append(generate_test_case(*scenario))

    content = HEADER + "\n".join(tests)

    output_path.write_text(content)
    print(f"Generated {len(tests)} test cases -> {output_path}")


if __name__ == "__main__":
    main()
