#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2026 Gustavo Amigo
#
# generate_tests.py — Generates prove_plugin.cpp from the scenario matrix.
#
# Usage:
#   python3 -m tests.proof.generate_tests
#   (from bytecaskdb-mariadb-plugin/)

import sys
from pathlib import Path
from textwrap import dedent, indent

from .scenario_matrix import (
    DMLShape, IndexShape, TxnShape, PluginFailureClass, generate_matrix
)
from .expected_delta import expected_delta
from .fault_point_resolver import resolve_fault

HEADER = '''\
// SPDX-License-Identifier: GPL-2.0-only
// Copyright (c) 2026 Gustavo Amigo
//
// prove_plugin.cpp — AUTO-GENERATED by tests/proof/generate_tests.py
// DO NOT EDIT BY HAND. Regenerate with:
//   cd bytecaskdb-mariadb-plugin && python3 -m tests.proof.generate_tests

#include "harness.h"
#include "fault_injector.h"

#include <catch2/catch_test_macros.hpp>

using namespace bytecaskdb::testing;
using namespace bytecask::testing;

'''


def table_spec_code(index: IndexShape) -> str:
    lines = ["TableSpec spec;", "spec.num_int_columns = 3;", "spec.has_pk = true;"]
    if index == IndexShape.one_nonunique:
        lines.append(
            "spec.secondary_indexes.push_back({1, 1, false, {1}});"
        )
    elif index == IndexShape.one_unique:
        lines.append(
            "spec.secondary_indexes.push_back({1, 1, true, {1}});"
        )
    return "\n  ".join(lines)


def setup_code(dml: DMLShape) -> str:
    """Code to set up pre-existing rows needed for update/delete."""
    if dml in (DMLShape.single_delete, DMLShape.single_update_index_change):
        return dedent("""\
            // Pre-insert a row to operate on.
            REQUIRE(h.insert_row({10, 20, 30}) == 0);
            REQUIRE(h.commit() == 0);
        """).rstrip()
    return ""


def dml_call(dml: DMLShape) -> str:
    if dml == DMLShape.single_insert:
        return "int rc = h.insert_row({100, 200, 300});"
    elif dml == DMLShape.single_delete:
        return "int rc = h.delete_row({10, 20, 30});"
    elif dml == DMLShape.single_update_index_change:
        return "int rc = h.update_row({10, 20, 30}, {10, 99, 30});"
    return "int rc = 0;"


def fault_setup(failure: PluginFailureClass) -> str:
    config = resolve_fault(failure)
    if config.injector_name:
        return f'ScopedFaultInjector guard("{config.injector_name}");'
    return ""


def fault_teardown(failure: PluginFailureClass) -> str:
    """Code after DML for ENGINE_DEGRADED tests — the fault fires at commit."""
    if failure == PluginFailureClass.ENGINE_DEGRADED:
        return "int commit_rc = h.commit();"
    return ""


def assertions(dml: DMLShape, index: IndexShape,
               failure: PluginFailureClass) -> str:
    delta = expected_delta(dml, index, TxnShape.autocommit, failure)
    lines = []

    if failure == PluginFailureClass.ENGINE_DEGRADED:
        lines.append("// DML buffers successfully; fault fires at commit.")
        lines.append("REQUIRE(rc == 0);")
        lines.append("REQUIRE(commit_rc != 0);")
    elif failure == PluginFailureClass.OCC_CONFLICT:
        lines.append("// OCC conflict — commit should fail.")
        lines.append("REQUIRE(rc == 0);")
    else:
        lines.append("REQUIRE(rc == 0);")
        if dml == DMLShape.single_insert:
            lines.append("REQUIRE(h.row_counter() == 1);")
        elif dml == DMLShape.single_delete:
            lines.append("// Row counter decremented after delete.")
            lines.append("REQUIRE(h.row_counter() == 0);")
        elif dml == DMLShape.single_update_index_change:
            lines.append("// Update does not change row count.")
            lines.append("REQUIRE(h.row_counter() == 1);")

    return "\n  ".join(lines)


def generate_test_case(dml: DMLShape, index: IndexShape,
                       txn: TxnShape, failure: PluginFailureClass) -> str:
    name = f"prove_plugin__{dml.name}__{index.name}__{txn.name}__{failure.name}"
    tag = "[prove_plugin]"

    spec = table_spec_code(index)
    setup = setup_code(dml)
    fault = fault_setup(failure)
    call = dml_call(dml)
    teardown = fault_teardown(failure)
    asserts = assertions(dml, index, failure)

    body_parts = [f"  {spec}", "  PluginTestHarness h(spec);"]
    if setup:
        body_parts.append(f"  {setup}")
    if fault:
        body_parts.append(f"  {fault}")
    body_parts.append(f"  {call}")
    if teardown:
        body_parts.append(f"  {teardown}")
    body_parts.append(f"  {asserts}")

    body = "\n\n".join(body_parts)

    return f'TEST_CASE("{name}", "{tag}") {{\n{body}\n}}\n'


def main():
    output_dir = Path(__file__).parent / "generated"
    output_dir.mkdir(exist_ok=True)
    output_path = output_dir / "prove_plugin.cpp"

    tests = []
    for scenario in generate_matrix():
        tests.append(generate_test_case(*scenario))

    content = HEADER + "\n".join(tests)

    output_path.write_text(content)
    print(f"Generated {len(tests)} test cases -> {output_path}")


if __name__ == "__main__":
    main()
