#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Gustavo Amigo
#
# Generates prove_vacuum_absorb.cpp from the vacuum_absorb scenario matrix.
#
# Usage (from project root):
#     python3 tests/proof/vacuum_absorb/generate_tests.py

from __future__ import annotations

import sys
from pathlib import Path
from typing import List

_project_root = Path(__file__).resolve().parent.parent.parent.parent
if str(_project_root) not in sys.path:
    sys.path.insert(0, str(_project_root))

from tests.proof.vacuum_absorb.expected_delta import (
    VacuumAbsorbDelta,
    vacuum_absorb_delta,
)
from tests.proof.vacuum_absorb.fault_point_resolver import resolve_absorb_fault
from tests.proof.vacuum_absorb.scenario_matrix import (
    AbsorbStateShape,
    VacuumAbsorbFailureClass,
    generate_matrix,
)

# ---------------------------------------------------------------------------
# C++ code generation
# ---------------------------------------------------------------------------


def gen_setup(state: AbsorbStateShape) -> str:
    """Generate C++ to create the initial DB state with a sealed file."""
    lines: List[str] = []
    lines.append(
        f"    // Setup: write {state.sealed_keys} to file_0, trigger rotation to seal it."
    )
    lines.append(
        f"    auto db = bytecask::DB::open(dir, {{.max_file_bytes = {state.max_file_bytes}}});"
    )
    for key in state.sealed_keys:
        lines.append(
            f'    db.put({{.sync = false}}, to_bytes("{key}"), to_bytes("v_{key}"));'
        )
    if state.deleted_keys:
        lines.append(f"    // Delete {state.deleted_keys} to create dead entries in file_0.")
        for key in state.deleted_keys:
            lines.append(
                f'    (void)db.del({{.sync = false}}, to_bytes("{key}"));'
            )
    return "\n".join(lines)


def gen_vacuum_call(fault_name: str | None, delta: VacuumAbsorbDelta) -> str:
    """Generate the vacuum() call, optionally wrapped in a fault injector."""
    # fragmentation_threshold=0.0 ensures any sealed file qualifies.
    # absorb_threshold=UINT64_MAX forces the absorb path.
    opts = (
        "{.fragmentation_threshold = 0.0, "
        ".absorb_threshold = std::numeric_limits<std::uint64_t>::max()}"
    )
    if fault_name is None or not delta.threw:
        # No fault, or fault is unreachable (e.g. all-dead → vacuum_remove path).
        return f"    REQUIRE(db.vacuum({opts}));"

    return (
        f"    {{\n"
        f'      bytecask::testing::ScopedFaultInjector fi{{"{fault_name}"}};\n'
        f"      REQUIRE_THROWS_AS(db.vacuum({opts}), std::system_error);\n"
        f"    }}"
    )


def gen_assertions(delta: VacuumAbsorbDelta) -> str:
    """Generate assert_vacuum_success or assert_vacuum_no_change."""
    if delta.file_removed:
        return (
            "    assert_vacuum_success(db, before, vacuumed_file_id);\n"
            "    CHECK_FALSE(db.is_degraded());"
        )
    return (
        "    assert_vacuum_no_change(db, before, vacuumed_file_id);\n"
        "    CHECK_FALSE(db.is_degraded());"
    )


def gen_test(state: AbsorbStateShape, failure: VacuumAbsorbFailureClass) -> str:
    """Generate one complete TEST_CASE."""
    delta = vacuum_absorb_delta(state, failure)
    fault_name = resolve_absorb_fault(failure)
    name = f"prove_vacuum_absorb__{state.label}__{failure.value}"

    parts: List[str] = []
    parts.append(f'TEST_CASE("{name}", "[prove_vacuum_absorb]") {{')
    parts.append("  TempDir td;")
    parts.append('  auto dir = td.path / "db";')
    parts.append("  bytecask::testing::VacuumBaseline before;")
    parts.append("  {")
    parts.append(gen_setup(state))
    parts.append("")
    parts.append("    before = capture_vacuum_baseline(db);")
    parts.append("    auto vacuumed_file_id = find_vacuum_target(db);")
    parts.append("")
    parts.append(gen_vacuum_call(fault_name, delta))
    parts.append("")
    parts.append(gen_assertions(delta))
    parts.append("  }")
    parts.append("  assert_vacuum_recoverable(dir, before);")
    parts.append("}")
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# File generation
# ---------------------------------------------------------------------------

FILE_HEADER = """\
// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Gustavo Amigo
//
// AUTO-GENERATED by tests/proof/vacuum_absorb/generate_tests.py — DO NOT EDIT.
//
// Correctness proof tests for vacuum_absorb_file(). Each test creates a
// DB with a sealed file, optionally injects a fault, calls vacuum(), and
// verifies the file was correctly absorbed or that the DB is clean on failure.

#include <limits>
#include <system_error>

#ifdef BYTECASK_TESTING
#include "fault_injector.h"
#endif
#include <catch2/catch_test_macros.hpp>

import bytecask;

#include "proof/invariants.h"

namespace {

using bytecask::testing::assert_consistent;
using bytecask::testing::assert_vacuum_no_change;
using bytecask::testing::assert_vacuum_recoverable;
using bytecask::testing::assert_vacuum_success;
using bytecask::testing::capture_vacuum_baseline;
using bytecask::testing::find_vacuum_target;
using bytecask::testing::to_bytes;

struct TempDir {
  std::filesystem::path path;
  TempDir()
      : path{std::filesystem::temp_directory_path() /
             std::format(
                 "prove_vac_absorb_{}_{}",
                 std::chrono::system_clock::now().time_since_epoch().count(),
                 next_id())} {
    std::filesystem::create_directories(path);
  }
  ~TempDir() { std::filesystem::remove_all(path); }
 private:
  static auto next_id() -> unsigned {
    static unsigned counter = 0;
    return counter++;
  }
};
};

} // namespace

"""


def generate_file() -> str:
    tests: List[str] = []
    for state, failure in generate_matrix():
        tests.append(gen_test(state, failure))
    return FILE_HEADER + "\n\n".join(tests) + "\n"


def main() -> None:
    output_dir = Path(__file__).resolve().parent.parent / "generated"
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / "prove_vacuum_absorb.cpp"
    content = generate_file()
    output_path.write_text(content)
    count = sum(1 for _ in generate_matrix())
    print(f"Generated {count} tests → {output_path}")


if __name__ == "__main__":
    main()
