#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Gustavo Amigo
#
# Generates prove_vacuum_compact.cpp from the vacuum_compact scenario matrix.
#
# Usage (from project root):
#     python3 tests/proof/vacuum_compact/generate_tests.py

from __future__ import annotations

import sys
from pathlib import Path
from typing import List

_project_root = Path(__file__).resolve().parent.parent.parent.parent
if str(_project_root) not in sys.path:
    sys.path.insert(0, str(_project_root))

from tests.proof.vacuum_compact.expected_delta import (
    VacuumCompactDelta,
    vacuum_compact_delta,
)
from tests.proof.vacuum_compact.fault_point_resolver import resolve_compact_fault
from tests.proof.vacuum_compact.scenario_matrix import (
    CompactStateShape,
    VacuumCompactFailureClass,
    generate_matrix,
)

# ---------------------------------------------------------------------------
# C++ code generation
# ---------------------------------------------------------------------------


def _build_open_opts(state: CompactStateShape) -> str:
    """Build the C++ designated-initializer list for Options from state fields."""
    parts = [f".max_file_bytes = {state.max_file_bytes}"]
    if state.use_mmap:
        parts.append(".use_mmap = true")
    if state.use_write_buffer:
        parts.append(".use_write_buffer = true")
    return ", ".join(parts)


def gen_setup(state: CompactStateShape) -> str:
    """Generate C++ to create the initial DB state with a sealed file."""
    lines: List[str] = []
    lines.append(
        f"    // Setup: write {state.sealed_keys} to file_0, trigger rotation to seal it."
    )
    opts = _build_open_opts(state)
    lines.append(
        f"    auto db = bytecask::DB::open(dir, {{{opts}}});"
    )
    for key in state.sealed_keys:
        lines.append(
            f'    db.put({{.sync = false}}, to_bytes("{key}"), to_bytes("v_{key}"));'
        )
    if state.deleted_keys:
        lines.append(
            f"    // Delete {state.deleted_keys} to create dead entries in file_0."
        )
        for key in state.deleted_keys:
            lines.append(
                f'    (void)db.del({{.sync = false}}, to_bytes("{key}"));'
            )
    return "\n".join(lines)


def gen_vacuum_call(
    fault_name: str | None, failure: VacuumCompactFailureClass
) -> str:
    """Generate the vacuum() call, wrapped in fault injector if needed."""
    # fragmentation_threshold=0.0 ensures any sealed file qualifies for vacuum.
    opts = "{.fragmentation_threshold = 0.0}"

    vc4_comment = (
        "\n    // VC4: rename succeeded — synced .data.tmp exists on disk but\n"
        "    // vacuum_commit never ran. Old file remains in state.\n"
        "    // assert_vacuum_recoverable confirms .data.tmp is not replayed."
        if failure == VacuumCompactFailureClass.VC4
        else ""
    )

    if fault_name is None:
        return f"    REQUIRE(db.vacuum({opts}));"

    return (
        f"    {{{vc4_comment}\n"
        f'      bytecask::testing::ScopedFaultInjector fi{{"{fault_name}"}};\n'
        f"      REQUIRE_THROWS_AS(db.vacuum({opts}), std::system_error);\n"
        f"    }}"
    )


def gen_assertions(delta: VacuumCompactDelta) -> str:
    if delta.file_removed:
        return (
            "    assert_vacuum_success(db, before, vacuumed_file_id);\n"
            "    CHECK_FALSE(db.is_degraded());"
        )
    return (
        "    assert_vacuum_no_change(db, before, vacuumed_file_id);\n"
        "    CHECK_FALSE(db.is_degraded());"
    )


def gen_test(
    state: CompactStateShape, failure: VacuumCompactFailureClass
) -> str:
    """Generate one complete TEST_CASE."""
    delta = vacuum_compact_delta(state, failure)
    fault_name = resolve_compact_fault(failure)
    name = f"prove_vacuum_compact__{state.label}__{failure.value}"

    parts: List[str] = []
    parts.append(f'TEST_CASE("{name}", "[prove_vacuum_compact]") {{')
    parts.append("  TempDir td;")
    parts.append('  auto dir = td.path / "db";')
    parts.append("  bytecask::testing::VacuumBaseline before;")
    parts.append("  {")
    parts.append(gen_setup(state))
    parts.append("")
    parts.append("    before = capture_vacuum_baseline(db);")
    parts.append("    auto vacuumed_file_id = find_vacuum_target(db);")
    parts.append("")
    parts.append(gen_vacuum_call(fault_name, failure))
    parts.append("")
    parts.append(gen_assertions(delta))
    parts.append("  }")
    opts = _build_open_opts(state)
    parts.append(f"  assert_vacuum_recoverable(dir, before, {{{opts}}});")
    parts.append("}")
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# File generation
# ---------------------------------------------------------------------------

FILE_HEADER = """\
// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Gustavo Amigo
//
// AUTO-GENERATED by tests/proof/vacuum_compact/generate_tests.py — DO NOT EDIT.
//
// Correctness proof tests for vacuum_compact_file(). Each test creates a
// DB with a sealed file, optionally injects a fault, calls vacuum(), and
// verifies the file was correctly compacted or that the DB is clean on failure.
// VC4 additionally verifies that an orphaned .data.tmp is not replayed on recovery.

#include <system_error>

#ifdef BYTECASK_TESTING
#include "fault_injector.h"
#endif
#include <catch2/catch_test_macros.hpp>

import bytecask;

#include "proof/invariants.h"

namespace {

using bytecask::testing::assert_consistent;
using bytecask::testing::assert_vacuum_no_change;
using bytecask::testing::assert_vacuum_recoverable;
using bytecask::testing::assert_vacuum_success;
using bytecask::testing::capture_vacuum_baseline;
using bytecask::testing::find_vacuum_target;
using bytecask::testing::to_bytes;

struct TempDir {
  std::filesystem::path path;
  TempDir()
      : path{std::filesystem::temp_directory_path() /
             std::format(
                 "prove_vac_compact_{}_{}",
                 std::chrono::system_clock::now().time_since_epoch().count(),
                 next_id())} {
    std::filesystem::create_directories(path);
  }
  ~TempDir() { std::filesystem::remove_all(path); }
 private:
  static auto next_id() -> unsigned {
    static unsigned counter = 0;
    return counter++;
  }
};

} // namespace

"""


def generate_file() -> str:
    tests: List[str] = []
    for state, failure in generate_matrix():
        tests.append(gen_test(state, failure))
    return FILE_HEADER + "\n\n".join(tests) + "\n"


def main() -> None:
    output_dir = Path(__file__).resolve().parent.parent / "generated"
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / "prove_vacuum_compact.cpp"
    content = generate_file()
    output_path.write_text(content)
    count = sum(1 for _ in generate_matrix())
    print(f"Generated {count} tests → {output_path}")


if __name__ == "__main__":
    main()
