name: Release

on:
  release:
    types: [published]

jobs:
  build-python:
    uses: ./.github/workflows/build-wheels.yml
    with:
      version: ${{ github.event.release.tag_name }}

  publish-python:
    needs: build-python
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: wheel-*
          merge-multiple: true

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist

  publish-node:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODO Node publishing"

  publish-mariadb:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODO MariaDB publishing"

  publish-cpp:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODO C++ publishing"
